### ISSUE TITLE
Convert between vector and coordz

### ISSUE THREAD

**Issue by lizhuoran1019** [signetlabdei/WOSS#9] opened 2022-05-30 08:20 UTC
Hi, there seems to be some problems with the conversion between vector and coordz, I'm not sure if my usage is wrong.
Below is my test code, I think coordz2 should be the same as coordz, but they are not the same, especially the depth is very different.
```
auto coordz = woss::CoordZ(40, 10, 0);
auto vect = CreateVectorFromCoordZ(coordz);
auto coordz2 = CreateCoordZFromVector(vect);

std::cout << "coordz: " << coordz << std::endl;
std::cout << "vect: " << vect << std::endl;
std::cout << "coordz2: " << coordz2 << std::endl;
```

Here is the result: 
```
coordz: Latitude = 40; Longitude = 10; Depth = 0; Marsden square = 180; Marsden One Degree square = 0
vect: 4.80632e+06:847485:4.0952e+06
coordz2: Latitude = 40.1896; Longitude = 10; Depth = 1724.76; Marsden square = 180; Marsden One Degree square = 9
```

**Comment by MetalKnight** [comment] 2022-05-31 07:57
@lizhuoran1019 thanks, issue confirmed.
CreateCoordZFromVector has been recently updated to WGS model while getCartX() etc... are still using spherical coordinates.
I will try to release a patch for you to test probably by the end of this week.

Side effect of #7

**Comment by lizhuoran1019** [comment] 2022-05-31 10:54
Thank you for your reply.
I'm looking forward to using the updated woss library.

**Comment by MetalKnight** [comment] 2022-06-03 07:05
@lizhuoran1019 patch will have some delay since I'm re-working the coord-to-cart conversion and back.
In the meanwhile, taking the definition of CoordZ::getCoordZFromCartesianCoords from previous WOSS release / git commit, should temporarily solve the issue.
Let me know if this worked for you.

**Comment by MetalKnight** [comment] 2022-06-03 08:41
@lizhuoran1019 I will post the final patch for you to test next week.
Cheers

**Comment by MetalKnight** [comment] 2022-06-04 11:03
@lizhuoran1019 please test the attached .diff file and confirm that the issue is solved also at your side.
After confirmation I will proceed with a new WOSS release.
thanks again
[coords_final.zip](https://github.com/signetlabdei/WOSS/files/8837539/coords_final.zip)

**Comment by lizhuoran1019** [comment] 2022-06-07 03:02
Sorry, I'm not very good at git. When I apply the diff file using the command below, it shows some conflicts. Is there any git command to resolve these conflicts? Or can I just modify these conflicts manually?
![image](https://user-images.githubusercontent.com/43104914/172286062-32da2fd8-4f8e-41aa-b0c1-008a42ec33f5.png)
![image](https://user-images.githubusercontent.com/43104914/172286494-f2c9eda4-974b-4622-a6e3-92e0eed95c18.png)
![image](https://user-images.githubusercontent.com/43104914/172286457-ca692778-b638-4ed0-9aa6-7cc21a7ecb54.png)

**Comment by MetalKnight** [comment] 2022-06-07 06:53
@lizhuoran1019 are you applying the diff to the latest version of woss?

**Comment by MetalKnight** [comment] 2022-06-07 07:08
@lizhuoran1019 please update woss to latest release and copy paste the attached files
[woss_patched_files.zip](https://github.com/signetlabdei/WOSS/files/8850895/woss_patched_files.zip)

**Comment by lizhuoran1019** [comment] 2022-06-07 07:20
Thanks a lot, I installed it successfully. 
But when I use the same test code as before in ns3, it shows the following error:
```
C:\WINDOWS\system32\wsl.exe --distribution ubuntu-20.04-lts --exec /bin/bash -c "cd /home/lzr/ns-3-allinone/ns-3-dev/build/scratch && /home/lzr/ns-3-allinone/ns-3-dev/build/scratch/ns3-dev-woss-coordz-test-debug"
/home/lzr/ns-3-allinone/ns-3-dev/build/scratch/ns3-dev-woss-coordz-test-debug: symbol lookup error: /home/lzr/ns-3-allinone/ns-3-dev/build/lib/libns3-dev-woss-ns3-debug.so: undefined symbol: _ZNK4woss6CoordZ8getCartZEv

进程已结束,退出代码127
```

**Comment by MetalKnight** [comment] 2022-06-07 07:22
@lizhuoran1019  re-compile re-link and re-install woss-ns3 as well first, then retry again.

**Comment by lizhuoran1019** [comment] 2022-06-07 08:41
I tried a few times, but it always shows an error like this:
![image](https://user-images.githubusercontent.com/43104914/172336696-5bbdd785-3be0-4139-b7aa-5dca0e1f2912.png)

**Comment by MetalKnight** [comment] 2022-06-07 08:47
@lizhuoran1019 did you re-compile, re-installed WOSS first, and then woss-ns3 on top of the patched WOSS?
woss-ns3 needs to link against the newly patched WOSS libraries

**Comment by lizhuoran1019** [comment] 2022-06-07 08:50
Yes, I have recompiled and installed woss according to the instructions in the WOSS/INSTALL file. 
Maybe there is some problem with my operation, I will try again.

**Comment by MetalKnight** [comment] 2022-06-07 08:51
I will re-check on my side later during the day.

**Comment by MetalKnight** [comment] 2022-06-07 18:09
@lizhuoran1019 I'm sorry but there is something wrong on your side.

this is what I did on my side, I've:
- installed WOSS prerequisites as per WOSS instructions (bellhop, NetCDF4 etc...)
- cloned this very public WOSS repository
- overwritten the THREE files that I gave you:
-- `woss/woss_def/coordinates-definitions.h`
-- `woss/woss_def/coordinates-definitions.cpp`
-- `tests/woss-coord-definitions-test.cpp`
- configured it with `./configure --with-pthread --with-ns-allinone=<path> --with-nsmiracle=/<path> --with-netcdf4=<path> --prefix=<path>` as written in WOSS doxygen docs
- performed `make` then `make check` then `make install`

then I've:
- cloned ns-3-dev repository
- aligned the repo to release 3.35 with `git checkout ns-3.35`, which is the last release with waf support. (woss-ns3 will soon have cmake support)
- cloned woss-ns3 repository into /src and configured it with the correct path, pointing them out to NetCDF4 and WOSS repo previously downloaded
 `./waf configure -d debug --enable-examples --enable-tests --with-woss-source=<path> --with-woss-library=<path> --with-netcdf4-install=<path> CXXFLAGS="-Wall -Werror -Wno-unused-variable"`
- then ran `./waf --run=woss-aloha-example`
-- which gave me the correct output

```
WossManagerResDbMT::checkConcurrentThreads() 3
WossManagerResDbMT::checkConcurrentThreads() 3
Received a packet of size 1000 bytes
Received a total of 1000 bytes at sink
```

So please perform these steps first and then continue with your custom scratch test.

**Comment by lizhuoran1019** [comment] 2022-06-08 02:43
It worked!!!
My problem may be caused by not using --with-ns-allinone=.
Thank you very much for your reply and help.

**Comment by MetalKnight** [comment] 2022-06-08 20:34
@lizhuoran1019 WOSS 1.12.3 has been released with the final fix.
I'm closing this issue

**Closed as completed by MetalKnight** 2022-06-08 20:34 UTC
